function [scenario, egoVehicle] = design_scene_0()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.7 (R2019b) and Automated Driving Toolbox 3.0 (R2019b).
% Generated on: 03-Oct-2020 08:09:50

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [1081 0 0;
    -891 0 0];
roadWidth = 50;
road(scenario, roadCenters, roadWidth);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-806 -15 0]);
waypoints = [-806 -15 0;
    1000 -14 0];
speed = 30;
trajectory(egoVehicle, waypoints, speed);

